source "https://rubygems.org"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "redis", "~> 5.0"
gem "ruby-kafka", "~> 1.5"
gem "telegram-bot-ruby", "~> 1.0"
gem "rack-cors"
gem "jbuilder", "~> 2.11"
gem "bootsnap", ">= 1.4.4", require: false
gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
end
